; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "tinyMediaManager"
#ifndef MyAppVersionNum
  #define MyAppVersionNum "5.0.0.0"
#endif
#ifndef MyAppVersionText
  #define MyAppVersionText "5.0.0.0"
#endif
#define MyAppPublisher "Manuel Laggner"
#define MyAppURL "https://www.tinymediamanager.org/"
#define MyAppExeName "tinyMediaManager.exe"
#define Year GetDateTimeString('yyyy', '', '');

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DA6AE47C-B91D-4C9D-A582-9B8DD433256C}
AppName={#MyAppName}
AppVersion={#MyAppVersionText}
AppVerName={#MyAppName} {#MyAppVersionText}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
VersionInfoCopyright=© 2012-{#Year} {#MyAppPublisher}
VersionInfoVersion={#MyAppVersionNum}
DefaultDirName={userpf}\{#MyAppName}V5
DisableProgramGroupPage=yes
LicenseFile=LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName}-{#MyAppVersionText}-Setup
SetupIconFile=tmm.ico
Compression=lzma2/ultra
SolidCompression=yes
; https://jrsoftware.org/ishelp/index.php?topic=setup_wizardstyle
WizardStyle=modern windows11 dynamic
; When set to auto, the dialog will only be displayed if Setup does not find a language identifier match. Simple drop-down, not fancy enough to activate :p
ShowLanguageDialog=no
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
; use all official languages from InnoSetup.
; remove the ones, where TMM does not have a resource bundle for.
; so that you cannot choose a language which is not available afterwards ;)
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "ar"; MessagesFile: "compiler:Languages\Arabic.isl"
;Name: "hy"; MessagesFile: "compiler:Languages\Armenian.isl"
;Name: "bg"; MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: "ca"; MessagesFile: "compiler:Languages\Catalan.isl"
;Name: "co"; MessagesFile: "compiler:Languages\Corsican.isl"
Name: "cs"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "da"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "nl"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "fi"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"
Name: "de"; MessagesFile: "compiler:Languages\German.isl"
Name: "he"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hu"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "it"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "ja"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "ko"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "no"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "pl"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "pt"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "ru"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "sk"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "sl"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "es"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "sv"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "ta"; MessagesFile: "compiler:Languages\Tamil.isl"
Name: "th"; MessagesFile: "compiler:Languages\Thai.isl"
Name: "tr"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "uk"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "*";  Excludes: "Output,*.iss,tmm.ico"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[InstallDelete]
; cleanup possible left-overs from former installation BEFORE installing
Type: filesandordirs; Name: "{app}\lib"
Type: filesandordirs; Name: "{app}\update"

[UninstallDelete]
Type: filesandordirs; Name: "{app}\jre"
Type: filesandordirs; Name: "{app}\templates"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent
